/* ============================================================
   curriculum.js — the syllabus.
   Adding a lesson = add an entry here + drop a .md file in content/.
   ============================================================ */
window.CURRICULUM = {
  title: 'Webcraft',
  blurb: 'A hands-on course in HTML, CSS, JavaScript, SQL and the tools around them. ' +
         'Every lesson explains the idea, shows real code you can edit and run right here, ' +
         'and ends with questions that check you actually got it.',

  howto: [
    '- **Read, then break something.** Code blocks marked *Live editor* really run. Change them, hit Run, see what happens. Breaking things on purpose is the fastest way to learn what a rule actually does.',
    '- **Do the exercises.** They are short on purpose. Attempt each one before reading on.',
    '- **Answer the quizzes honestly.** Getting one wrong and reading why is worth more than getting it right by luck.',
    '- **Mark lessons complete** as you go — progress is saved in this browser, so the sidebar always shows where you left off.',
    '- **Order matters less than momentum.** The tracks build on each other, but if CSS Grid is what you need today, jump straight there.',
    '',
    'One honest warning: you cannot learn to code by reading alone, any more than you can learn to swim from a poolside lecture. Keep a scratch file open and type things out.'
  ].join('\n'),

  tracks: [
    {
      id: 'foundations',
      name: 'Foundations',
      emoji: '🌍',
      blurb: 'What the web actually is, how a page gets to your screen, and the tools you will live in.',
      lessons: [
        { id: 'how-the-web-works', title: 'How the web works', minutes: 9, tags: ['concepts'],
          summary: 'Clients, servers, DNS and what really happens when you type a URL.',
          file: 'content/foundations/how-the-web-works.md' },
        { id: 'http-and-urls', title: 'HTTP, URLs and status codes', minutes: 10, tags: ['http'],
          summary: 'The request/response conversation every web app is built on.',
          file: 'content/foundations/http-and-urls.md' },
        { id: 'frontend-vs-backend', title: 'Front end, back end and the stack', minutes: 8, tags: ['concepts'],
          summary: 'Who does what, where code runs, and what "full stack" means in practice.',
          file: 'content/foundations/frontend-vs-backend.md' },
        { id: 'your-toolkit', title: 'Setting up your toolkit', minutes: 9, tags: ['tools'],
          summary: 'Editor, folder structure, file naming and a first working project.',
          file: 'content/foundations/your-toolkit.md' },
        { id: 'devtools', title: 'Browser DevTools', minutes: 10, tags: ['tools', 'debugging'],
          summary: 'Inspect elements, edit CSS live, read the console and watch the network.',
          file: 'content/foundations/devtools.md' },
        { id: 'how-to-learn', title: 'How to get unstuck', minutes: 8, tags: ['mindset'],
          summary: 'Reading error messages, searching well, and debugging like an engineer.',
          file: 'content/foundations/how-to-learn.md' }
      ]
    },
    {
      id: 'html',
      name: 'HTML',
      emoji: '🧱',
      blurb: 'The structure and meaning of a page. Boring to look at, impossible to skip.',
      lessons: [
        { id: 'html-first-page', title: 'Your first HTML page', minutes: 10, tags: ['html', 'basics'],
          summary: 'Tags, elements, attributes and the skeleton every page shares.',
          file: 'content/html/html-first-page.md' },
        { id: 'html-text', title: 'Text: headings, paragraphs and meaning', minutes: 9, tags: ['html'],
          summary: 'Marking up prose so both people and machines understand it.',
          file: 'content/html/html-text.md' },
        { id: 'html-links-images', title: 'Links, images and media', minutes: 11, tags: ['html'],
          summary: 'Hyperlinks, paths, responsive images, video and audio.',
          file: 'content/html/html-links-images.md' },
        { id: 'html-lists-tables', title: 'Lists and tables', minutes: 9, tags: ['html'],
          summary: 'Ordered data done properly — including accessible table markup.',
          file: 'content/html/html-lists-tables.md' },
        { id: 'html-forms', title: 'Forms and inputs', minutes: 14, tags: ['html', 'forms'],
          summary: 'Collecting input: every field type, labels, and built-in validation.',
          file: 'content/html/html-forms.md' },
        { id: 'html-semantics', title: 'Semantic HTML and document structure', minutes: 10, tags: ['html', 'a11y'],
          summary: 'header, nav, main, article, section — and when a div is still fine.',
          file: 'content/html/html-semantics.md' },
        { id: 'html-accessibility', title: 'Accessibility essentials', minutes: 12, tags: ['a11y'],
          summary: 'Keyboard support, alt text, ARIA, contrast — the parts that matter most.',
          file: 'content/html/html-accessibility.md' },
        { id: 'html-head-seo', title: 'The head: metadata, SEO and sharing', minutes: 9, tags: ['html', 'seo'],
          summary: 'Titles, descriptions, favicons, Open Graph and what search engines read.',
          file: 'content/html/html-head-seo.md' }
      ]
    },
    {
      id: 'css',
      name: 'CSS',
      emoji: '🎨',
      blurb: 'Layout, colour, type and motion — from the box model to Grid and modern CSS.',
      lessons: [
        { id: 'css-getting-started', title: 'CSS from zero', minutes: 10, tags: ['css', 'basics'],
          summary: 'Rules, selectors, declarations and the three ways to attach CSS.',
          file: 'content/css/css-getting-started.md' },
        { id: 'css-selectors', title: 'Selectors in depth', minutes: 12, tags: ['css'],
          summary: 'Classes, combinators, pseudo-classes, pseudo-elements and :has().',
          file: 'content/css/css-selectors.md' },
        { id: 'css-cascade', title: 'The cascade, specificity and inheritance', minutes: 12, tags: ['css'],
          summary: 'Why your style "isn’t working", explained properly.',
          file: 'content/css/css-cascade.md' },
        { id: 'css-box-model', title: 'The box model', minutes: 11, tags: ['css'],
          summary: 'Content, padding, border, margin — and border-box sanity.',
          file: 'content/css/css-box-model.md' },
        { id: 'css-units-colors', title: 'Units, colours and values', minutes: 10, tags: ['css'],
          summary: 'px vs rem vs %, viewport units, colour notation and calc().',
          file: 'content/css/css-units-colors.md' },
        { id: 'css-typography', title: 'Typography', minutes: 10, tags: ['css'],
          summary: 'Font stacks, web fonts, line length, rhythm and readable text.',
          file: 'content/css/css-typography.md' },
        { id: 'css-flow-display', title: 'Display, flow and positioning', minutes: 12, tags: ['css'],
          summary: 'Block vs inline, normal flow, position, z-index and stacking.',
          file: 'content/css/css-flow-display.md' },
        { id: 'css-flexbox', title: 'Flexbox', minutes: 13, tags: ['css', 'layout'],
          summary: 'One-dimensional layout: rows, columns, alignment and flexible sizing.',
          file: 'content/css/css-flexbox.md' },
        { id: 'css-grid', title: 'CSS Grid', minutes: 14, tags: ['css', 'layout'],
          summary: 'Two-dimensional layout, named areas and genuinely responsive grids.',
          file: 'content/css/css-grid.md' },
        { id: 'css-responsive', title: 'Responsive design', minutes: 12, tags: ['css', 'layout'],
          summary: 'Mobile first, media queries, fluid type and layouts that bend.',
          file: 'content/css/css-responsive.md' },
        { id: 'css-transitions', title: 'Transitions, transforms and animation', minutes: 11, tags: ['css'],
          summary: 'Motion that helps rather than annoys — and respects reduced-motion.',
          file: 'content/css/css-transitions.md' },
        { id: 'css-modern', title: 'Modern CSS and design systems', minutes: 12, tags: ['css'],
          summary: 'Custom properties, nesting, container queries, dark mode, clamp().',
          file: 'content/css/css-modern.md' },
        { id: 'css-architecture', title: 'Organising CSS at scale', minutes: 10, tags: ['css'],
          summary: 'Naming conventions, layers, resets, and how not to fear your stylesheet.',
          file: 'content/css/css-architecture.md' }
      ]
    },
    {
      id: 'javascript',
      name: 'JavaScript',
      emoji: '⚡',
      blurb: 'The language that makes pages think. From variables to async, DOM to modules.',
      lessons: [
        { id: 'js-getting-started', title: 'JavaScript from zero', minutes: 10, tags: ['js', 'basics'],
          summary: 'Where JS runs, how to load it, and your first lines of code.',
          file: 'content/js/js-getting-started.md' },
        { id: 'js-variables-types', title: 'Variables and types', minutes: 12, tags: ['js'],
          summary: 'let, const, strings, numbers, booleans, null, undefined — and coercion.',
          file: 'content/js/js-variables-types.md' },
        { id: 'js-operators-conditionals', title: 'Operators and conditionals', minutes: 11, tags: ['js'],
          summary: 'Comparison, truthiness, if/else, ternaries and logical operators.',
          file: 'content/js/js-operators-conditionals.md' },
        { id: 'js-loops', title: 'Loops and iteration', minutes: 10, tags: ['js'],
          summary: 'for, while, for...of, and when to reach for a loop at all.',
          file: 'content/js/js-loops.md' },
        { id: 'js-functions', title: 'Functions and scope', minutes: 13, tags: ['js'],
          summary: 'Declarations, arrows, parameters, return values, scope and closures.',
          file: 'content/js/js-functions.md' },
        { id: 'js-arrays', title: 'Arrays and array methods', minutes: 13, tags: ['js'],
          summary: 'map, filter, reduce, find, sort — the daily bread of JavaScript.',
          file: 'content/js/js-arrays.md' },
        { id: 'js-objects', title: 'Objects', minutes: 12, tags: ['js'],
          summary: 'Properties, nesting, destructuring, spread and reference semantics.',
          file: 'content/js/js-objects.md' },
        { id: 'js-dom', title: 'The DOM: reading and changing the page', minutes: 14, tags: ['js', 'dom'],
          summary: 'Selecting elements, changing content, classes, attributes and styles.',
          file: 'content/js/js-dom.md' },
        { id: 'js-events', title: 'Events and interactivity', minutes: 13, tags: ['js', 'dom'],
          summary: 'Listeners, the event object, bubbling, delegation and preventDefault.',
          file: 'content/js/js-events.md' },
        { id: 'js-forms', title: 'Working with forms in JavaScript', minutes: 12, tags: ['js', 'forms'],
          summary: 'Reading values, custom validation, FormData and submitting without a reload.',
          file: 'content/js/js-forms.md' },
        { id: 'js-async', title: 'Asynchronous JavaScript', minutes: 15, tags: ['js', 'async'],
          summary: 'The event loop, callbacks, promises and async/await without the fog.',
          file: 'content/js/js-async.md' },
        { id: 'js-fetch', title: 'Talking to APIs with fetch', minutes: 13, tags: ['js', 'async'],
          summary: 'GET and POST, JSON, error handling, loading states and CORS.',
          file: 'content/js/js-fetch.md' },
        { id: 'js-storage', title: 'Storing data in the browser', minutes: 10, tags: ['js'],
          summary: 'localStorage, sessionStorage, cookies and JSON serialisation.',
          file: 'content/js/js-storage.md' },
        { id: 'js-classes', title: 'Classes, prototypes and this', minutes: 12, tags: ['js'],
          summary: 'Object-oriented JavaScript, and the famous "this" confusion resolved.',
          file: 'content/js/js-classes.md' },
        { id: 'js-modules', title: 'Modules and modern syntax', minutes: 11, tags: ['js'],
          summary: 'import/export, optional chaining, template literals and other ES6+ wins.',
          file: 'content/js/js-modules.md' },
        { id: 'js-errors', title: 'Errors, debugging and defensive code', minutes: 11, tags: ['js', 'debugging'],
          summary: 'try/catch, reading stack traces, and the bugs everyone hits.',
          file: 'content/js/js-errors.md' }
      ]
    },
    {
      id: 'sql',
      name: 'SQL & databases',
      emoji: '🗄️',
      blurb: 'Store it, query it, keep it correct. Runs a real SQLite database in your browser.',
      lessons: [
        { id: 'sql-intro', title: 'What a database actually is', minutes: 10, tags: ['sql', 'basics'],
          summary: 'Tables, rows, columns, keys — and why not just use a spreadsheet.',
          file: 'content/sql/sql-intro.md' },
        { id: 'sql-select', title: 'SELECT: asking for data', minutes: 11, tags: ['sql'],
          summary: 'Columns, aliases, expressions, DISTINCT and the shape of a query.',
          file: 'content/sql/sql-select.md' },
        { id: 'sql-where', title: 'Filtering with WHERE', minutes: 12, tags: ['sql'],
          summary: 'Comparisons, AND/OR, IN, BETWEEN, LIKE and the NULL trap.',
          file: 'content/sql/sql-where.md' },
        { id: 'sql-sorting', title: 'Sorting, limiting and paging', minutes: 9, tags: ['sql'],
          summary: 'ORDER BY, LIMIT/OFFSET and how pagination really works.',
          file: 'content/sql/sql-sorting.md' },
        { id: 'sql-aggregates', title: 'Aggregates and GROUP BY', minutes: 13, tags: ['sql'],
          summary: 'COUNT, SUM, AVG, grouping, HAVING — turning rows into answers.',
          file: 'content/sql/sql-aggregates.md' },
        { id: 'sql-joins', title: 'JOINs: combining tables', minutes: 15, tags: ['sql'],
          summary: 'INNER, LEFT, self joins, and a mental model that makes them click.',
          file: 'content/sql/sql-joins.md' },
        { id: 'sql-subqueries', title: 'Subqueries and CTEs', minutes: 12, tags: ['sql'],
          summary: 'Queries inside queries, WITH clauses and readable SQL.',
          file: 'content/sql/sql-subqueries.md' },
        { id: 'sql-writing', title: 'INSERT, UPDATE, DELETE and transactions', minutes: 12, tags: ['sql'],
          summary: 'Changing data safely, and why transactions exist.',
          file: 'content/sql/sql-writing.md' },
        { id: 'sql-schema', title: 'Designing a schema', minutes: 14, tags: ['sql', 'design'],
          summary: 'Data types, keys, relationships, normalisation and constraints.',
          file: 'content/sql/sql-schema.md' },
        { id: 'sql-indexes', title: 'Indexes and query performance', minutes: 11, tags: ['sql'],
          summary: 'Why queries get slow, what an index does, and when not to add one.',
          file: 'content/sql/sql-indexes.md' },
        { id: 'sql-in-apps', title: 'Using SQL from an application', minutes: 12, tags: ['sql', 'security'],
          summary: 'Parameterised queries, SQL injection, ORMs and the N+1 problem.',
          file: 'content/sql/sql-in-apps.md' }
      ]
    },
    {
      id: 'backend',
      name: 'Backend & tooling',
      emoji: '🛠️',
      blurb: 'Git, Node, APIs, auth, deployment, security, performance and tests.',
      lessons: [
        { id: 'git', title: 'Git and GitHub', minutes: 14, tags: ['tools', 'git'],
          summary: 'Commits, branches, merges, pull requests and undoing mistakes.',
          file: 'content/backend/git.md' },
        { id: 'node-npm', title: 'Node.js and npm', minutes: 12, tags: ['node'],
          summary: 'JavaScript outside the browser, packages, scripts and package.json.',
          file: 'content/backend/node-npm.md' },
        { id: 'build-an-api', title: 'Building a web server and API', minutes: 15, tags: ['node', 'api'],
          summary: 'Routes, request handling and a working CRUD API in Express.',
          file: 'content/backend/build-an-api.md' },
        { id: 'rest-json', title: 'REST, JSON and API design', minutes: 11, tags: ['api'],
          summary: 'Resources, verbs, status codes and designing an API people can use.',
          file: 'content/backend/rest-json.md' },
        { id: 'auth', title: 'Authentication and sessions', minutes: 13, tags: ['api', 'security'],
          summary: 'Password hashing, cookies, sessions, JWTs and staying logged in.',
          file: 'content/backend/auth.md' },
        { id: 'security', title: 'Web security essentials', minutes: 13, tags: ['security'],
          summary: 'XSS, CSRF, injection, secrets, HTTPS and headers that protect you.',
          file: 'content/backend/security.md' },
        { id: 'performance', title: 'Performance and Core Web Vitals', minutes: 12, tags: ['performance'],
          summary: 'Why pages feel slow, what to measure, and the fixes that pay off.',
          file: 'content/backend/performance.md' },
        { id: 'testing', title: 'Testing your code', minutes: 12, tags: ['testing'],
          summary: 'Unit, integration and end-to-end tests — and what is worth testing.',
          file: 'content/backend/testing.md' },
        { id: 'deploying', title: 'Deploying to the real internet', minutes: 12, tags: ['devops'],
          summary: 'Static hosts, servers, domains, HTTPS, environments and CI.',
          file: 'content/backend/deploying.md' },
        { id: 'frameworks', title: 'Frameworks: React and friends', minutes: 12, tags: ['frameworks'],
          summary: 'What problem frameworks solve, how React thinks, and when to skip them.',
          file: 'content/backend/frameworks.md' }
      ]
    },
    {
      id: 'projects',
      name: 'Build & next steps',
      emoji: '🚀',
      blurb: 'Put it together in real projects, then decide where to go next.',
      lessons: [
        { id: 'project-portfolio', title: 'Project: a personal site', minutes: 20, tags: ['project'],
          summary: 'Build and ship a responsive, accessible portfolio page from scratch.',
          file: 'content/projects/project-portfolio.md' },
        { id: 'project-task-app', title: 'Project: an interactive task app', minutes: 25, tags: ['project'],
          summary: 'State, rendering, events and persistence in one small app.',
          file: 'content/projects/project-task-app.md' },
        { id: 'whats-next', title: 'Where to go from here', minutes: 9, tags: ['career'],
          summary: 'A realistic roadmap, good resources and how to keep improving.',
          file: 'content/projects/whats-next.md' }
      ]
    }
  ]
};
